version: '3.3'

services:
  php:
    depends_on:
      - mysql
    image: webdevops/php-apache-dev:7.4
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_MEMORY_LIMIT: 4G
    ports:
      - 80:80
    links:
      - mysql
    working_dir: '/app'

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms2
      MYSQL_USER: cms
      MYSQL_PASSWORD: cms

#  composer:
#    image: composer:latest
#    volumes:
#      - ./:/app

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - 8088:80
    volumes:
      - /sessions
    links:
      - mysql

volumes:
  db_data:
  app: